### ISSUE TITLE
Issue running setup

### ISSUE THREAD

**Issue by codethread** [AHDesigns/js-gen#9]
Console.log s are not appearing and then

```
TypeError: util.getSystemErrorName is not a function
    at getCode (/Users/fde10/.nvm/versions/node/v9.5.0/lib/node_modules/@ahdesigns/js-gen/node_modules/execa/lib/error.js:11:16)
    at makeError (/Users/fde10/.nvm/versions/node/v9.5.0/lib/node_modules/@ahdesigns/js-gen/node_modules/execa/lib/error.js:50:35)
    at handlePromise (/Users/fde10/.nvm/versions/node/v9.5.0/lib/node_modules/@ahdesigns/js-gen/node_modules/execa/index.js:112:26)
    at <anonymous>
```

**Comment by codethread** [comment]
Issue was an unsupported node version
